# apply window.opacity to all backgrounds (i.e. including nvim)
[colors]
transparent_background_colors = true

[window]
opacity = 0.95

[cursor.style]
shape   = "Beam"

# ========== FONTS ==========

# HackNerdFont
# JetBrainsMono Nerd Font
# MesloLGS NF

[font.normal]
family  = "MesloLGS NF"
style   = "Regular"

[font.bold]
family  = "MesloLGS NF"
style   = "Bold"

[font.bold_italic]
family  = "MesloLGS NF"
style   = "Bold Italic"

[font.italic]
family  = "MesloLGS NF"
style   = "Italic"

# ========== set bindings for neovim to use ==========

[keyboard]
bindings = [
  # special keys
  { key = "Tab",   mods = "Control", chars = "\u001b[27;5;9~"},
  { key = "Tab",   mods = "Control|Shift", chars = "\u001b[27;6;9~"},
  { key = "Enter", mods = "Control", chars = "\u001b[27;5;13~"},
  { key = "Enter", mods = "Control|Shift", chars = "\u001b[27;6;13~"},

  # control+shift+letter -- I/M reserved for <ESC>/<CR>
  { key = "A", mods = "Control|Shift", chars = "\u001b[27;6;1~"},
  { key = "B", mods = "Control|Shift", chars = "\u001b[27;6;2~"},
  { key = "C", mods = "Control|Shift", chars = "\u001b[27;6;3~"},
  { key = "D", mods = "Control|Shift", chars = "\u001b[27;6;4~"},
  { key = "E", mods = "Control|Shift", chars = "\u001b[27;6;5~"},
  { key = "F", mods = "Control|Shift", chars = "\u001b[27;6;6~"},
  { key = "G", mods = "Control|Shift", chars = "\u001b[27;6;7~"},
  { key = "H", mods = "Control|Shift", chars = "\u001b[27;6;8~"},
  { key = "J", mods = "Control|Shift", chars = "\u001b[27;6;10~"},
  { key = "K", mods = "Control|Shift", chars = "\u001b[27;6;11~"},
  { key = "L", mods = "Control|Shift", chars = "\u001b[27;6;12~"},
  { key = "N", mods = "Control|Shift", chars = "\u001b[27;6;14~"},
  { key = "O", mods = "Control|Shift", chars = "\u001b[27;6;15~"},
  { key = "P", mods = "Control|Shift", chars = "\u001b[27;6;16~"},
  { key = "Q", mods = "Control|Shift", chars = "\u001b[27;6;17~"},
  { key = "R", mods = "Control|Shift", chars = "\u001b[27;6;18~"},
  { key = "S", mods = "Control|Shift", chars = "\u001b[27;6;19~"},
  { key = "T", mods = "Control|Shift", chars = "\u001b[27;6;20~"},
  { key = "U", mods = "Control|Shift", chars = "\u001b[27;6;21~"},
  { key = "V", mods = "Control|Shift", chars = "\u001b[27;6;22~"},
  { key = "W", mods = "Control|Shift", chars = "\u001b[27;6;23~"},
  { key = "X", mods = "Control|Shift", chars = "\u001b[27;6;24~"},
  { key = "Y", mods = "Control|Shift", chars = "\u001b[27;6;25~"},
  { key = "Z", mods = "Control|Shift", chars = "\u001b[27;6;26~"},

  # control + number
  { key = "0", mods = "Control", chars = "\u001b[27;5;48~"},
  { key = "1", mods = "Control", chars = "\u001b[27;5;49~"},
  { key = "2", mods = "Control", chars = "\u001b[27;5;50~"},
  { key = "3", mods = "Control", chars = "\u001b[27;5;51~"},
  { key = "4", mods = "Control", chars = "\u001b[27;5;52~"},
  { key = "5", mods = "Control", chars = "\u001b[27;5;53~"},
  { key = "6", mods = "Control", chars = "\u001b[27;5;54~"},
  { key = "7", mods = "Control", chars = "\u001b[27;5;55~"},
  { key = "8", mods = "Control", chars = "\u001b[27;5;56~"},
  { key = "9", mods = "Control", chars = "\u001b[27;5;57~"},
]

# # ---- Markdown Specific ----
#
# # renumber markdown list
# [[keyboard.bindings]]
# key   = "2"
# mods  = "Control"
# chars = "\u00B2"
#
# # markdown checkbox toggle
# [[keyboard.bindings]]
# key   = "3"
# mods  = "Control"
# chars = "\u00B3"

# ============================================================ 
#                        colour schemes
# ============================================================ 

# =============== Tokyo Night ===============
[colors.primary]
foreground = '#c0caf5'
# background = '#1a1b26'

[colors.cursor]
cursor = '#c0caf5'
text   = '#1a1b26'

[colors.normal]
black   = '#15161e'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#bb9af7'
cyan    = '#7dcfff'
white   = '#a9b1d6'

[colors.bright]
black   = '#414868'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#bb9af7'
cyan    = '#7dcfff'
white   = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

# =============== Catppuccin ===============
# [colors.primary]
# background = "#1e1e2e"
# foreground = "#cdd6f4"
# dim_foreground = "#7f849c"
# bright_foreground = "#cdd6f4"
#
# [colors.cursor]
# text = "#1e1e2e"
# cursor = "#f5e0dc"
#
# [colors.vi_mode_cursor]
# text = "#1e1e2e"
# cursor = "#b4befe"
#
# [colors.search.matches]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.search.focused_match]
# foreground = "#1e1e2e"
# background = "#a6e3a1"
#
# [colors.footer_bar]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.hints.start]
# foreground = "#1e1e2e"
# background = "#f9e2af"
#
# [colors.hints.end]
# foreground = "#1e1e2e"
# background = "#a6adc8"
#
# [colors.selection]
# text = "#1e1e2e"
# background = "#f5e0dc"
#
# [colors.normal]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
#
# [colors.bright]
# black = "#585b70"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#a6adc8"
#
# [colors.dim]
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#bac2de"
#
# [[colors.indexed_colors]]
# index = 16
# color = "#fab387"
#
# [[colors.indexed_colors]]
# index = 17
# color = "#f5e0dc"
